export const CHANGE_PAGE = "CHANGE_PAGE";
export const UPDATE_CURRENT_LINES = "UPDATE_CURRENT_LINES";
export const CHANGE_SELECTED_FILE = "CHANGE_SELECTED_FILE";
export const IS_LOADING = "IS_LOADING";
